### ISSUE TITLE
サンプルコンテンツのフォームがレガシーフォーム

### ISSUE THREAD

**Issue by hissy** [concrete5japan/theme_stucco#5]
エクスプレスフォームにできるようなら変更する

**Comment by pictron** [comment]
エクスプレスフォームを、content.xmlに入れてみたけどわからない。
IDを、CDATAで囲めばと思ったがダメだった。

＜フォーム部分＞
<block type="express_form" name="">
      <data table="btExpressForm">
          <record>
              <exFormID>cb50784c-b6e5-11ef-97b3-e0261d204707</exFormID>
              <submitLabel>Submit</submitLabel>
              <thankyouMsg>Thanks!</thankyouMsg>
              <notifyMeOnSubmission>0</notifyMeOnSubmission>
              <recipientEmail/>
              <displayCaptcha>1</displayCaptcha>
              <storeFormSubmission>1</storeFormSubmission>
              <redirectCID/><replyToEmailControlID/>
              <addFilesToSet>0</addFilesToSet>
              <addFilesToFolder>7</addFilesToFolder>
          </record>
      </data>
  </block>

＜エクプレスエントリー＞
<expressentities>
        <entity id="cb4cf546-b6e5-11ef-97b3-e0261d204707" handle="contact" plural_handle="" name="Contact" supports_custom_display_order="" include_in_public_list="" use_separate_site_result_buckets="" description="" default_view_form="cb50784c-b6e5-11ef-97b3-e0261d204707" default_edit_form="cb50784c-b6e5-11ef-97b3-e0261d204707" results-folder="/Forms">
            <attributekeys>
                <attributekey handle="first_name" name="First Name" package="" searchable="1" indexed="1" type="text" category="">
                    <type placeholder=""/>
                </attributekey>
                <attributekey handle="last_name" name="Last Name" package="" searchable="1" indexed="1" type="text" category="">
                    <type placeholder=""/>
                </attributekey>
                <attributekey handle="email_address" name="Email Address" package="" searchable="1" indexed="1" type="email" category=""/><attributekey handle="subject" name="Subject" package="" searchable="1" indexed="1" type="select" category="">
                    <type allow-multiple-values="" display-order="display_asc" display-multiple-values="" allow-other-values="" hide-none-option="1">
                        <options>
                            <option value="I love your work." is-end-user-added=""/>
                            <option value="Great website." is-end-user-added=""/>
                            <option value="Check out this cool thing I found." is-end-user-added=""/>
                            <option value="Other." is-end-user-added=""/>
                        </options>
                    </type>
                </attributekey>
                <attributekey handle="message" name="Message" package="" searchable="1" indexed="1" type="textarea" category="">
                    <type mode="text"/>
                </attributekey>
            </attributekeys>
            <forms>
                <form id="cb50784c-b6e5-11ef-97b3-e0261d204707" name="フォーム">
                    <fieldsets>
                        <fieldset title="" description="">
                            <controls>
                                <control id="d2d9d342-b6e5-11ef-97b3-e0261d204707" type="attribute_key" required="1" custom-label="">
                                    <attributekey handle="first_name"/>
                                </control>
                                <control id="dbed0dc8-b6e5-11ef-97b3-e0261d204707" type="attribute_key" required="1" custom-label="">
                                    <attributekey handle="last_name"/>
                                </control>
                                <control id="e8568364-b6e5-11ef-97b3-e0261d204707" type="attribute_key" required="1" custom-label="">
                                    <attributekey handle="email_address"/>
                                </control>
                                <control id="21e10500-b6e6-11ef-97b3-e0261d204707" type="attribute_key" required="" custom-label="">
                                    <attributekey handle="subject"/>
                                </control>
                                <control id="29d61ad4-b6e6-11ef-97b3-e0261d204707" type="attribute_key" required="" custom-label="">
                                    <attributekey handle="message"/>
                                </control>
                            </controls>
                        </fieldset>
                    </fieldsets>
                </form>
            </forms>
        </entity>
    </expressentities>

**Comment by pictron** [comment]
XMLでblockとエンティティ、ブロックIDをCDATAで囲ってcontent.xmlに入れてみたけど、ダメですね。express form、何か足りないかな？
